  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"


  [[main]]
  name = "Publications"
  weight = 200
  identifier = "publications"
  url = "/publications/"


  [[main]]
  name = "Accomplishments"
  weight = 300
  identifier = "accomplishments"
  url = "/accomplishments/"

  [[main]]
  name = "CV"
  weight = 400
  identifier = "cv"
  url = "/cv/"






